// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh86fSsDR6w4Z-fpRlZ36QP-l766O09zI',
    appId: '1:73077398421:web:37f4af9b3747ba837df49c',
    messagingSenderId: '73077398421',
    projectId: 'neosante-24dc4',
    authDomain: 'neosante-24dc4.firebaseapp.com',
    storageBucket: 'neosante-24dc4.firebasestorage.app',
    measurementId: 'G-JFK6GCEMCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtIRlmPB9oc4digjRwxIOWoQN52MkEN_Q',
    appId: '1:73077398421:android:fe53c3bc18f4f6877df49c',
    messagingSenderId: '73077398421',
    projectId: 'neosante-24dc4',
    storageBucket: 'neosante-24dc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl4Jnq3clzxBtl0YjrTKAlh2iIeR_y8ME',
    appId: '1:73077398421:ios:8f73122d360d8dc47df49c',
    messagingSenderId: '73077398421',
    projectId: 'neosante-24dc4',
    storageBucket: 'neosante-24dc4.firebasestorage.app',
    iosClientId: '73077398421-v70i75a1us6g53vbrk9lk0odql50ras3.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh86fSsDR6w4Z-fpRlZ36QP-l766O09zI',
    appId: '1:73077398421:web:fcae4b8772312a5f7df49c',
    messagingSenderId: '73077398421',
    projectId: 'neosante-24dc4',
    authDomain: 'neosante-24dc4.firebaseapp.com',
    storageBucket: 'neosante-24dc4.firebasestorage.app',
    measurementId: 'G-XX2FXQJ57G',
  );

}